### ISSUE TITLE
Using try/catch in tests

### ISSUE THREAD

**Issue by andrewstam** [carmen52/CS4500-A1-part2#2]
Looking at your tests for Queue, we noticed that you use try/catch statements to test that exceptions are thrown. We also designed an API for Queue and originally wrote our tests this way, but it was brought to our attention that CwC doesn't include throwing exceptions. This means that we have no way to pass the tests that use try/catch statements currently. Is it possible to change the tests, either expecting to return NULL for invalid get/remove/etc, or if you prefer us calling exit with an error code, removing those tests altogether (no way to test that a program has exited)?

Thanks!

**Comment by Gavazzi1** [comment]
Sure thing, thanks for bringing it up.  My partner isn't available right now and forgot to make me a collaborator, so I'll make the changes and link them in a new repo in just a minute. Once she's available we'll push the changes to this repo.

**Comment by Gavazzi1** [comment]
Update, I'll modify the spec to return nullptr if the Queue is empty. That'll also require changing the method signatures to return pointers instead of references.

**Comment by andrewstam** [comment]
Thanks for the quick response! I actually don't think nullptr is part of CwC either, but I think just using regular NULL would be accepted.

**Comment by Gavazzi1** [comment]
nullptr is allowed -- it's what dynamic_cast returns whenever it fails. Jan mentions it in post 77 on Piazza

**Comment by Gavazzi1** [comment]
Here's the temporary repo: https://github.com/Gavazzi1/CS4500-A2-Changes

We'll close this issue once the changes are integrated into this repo

**Comment by andrewstam** [comment]
Oh okay, sorry about the confusion. Thanks for the clarification! Sounds good.

**Comment by bacigaluped** [comment]
The removals of consts are much appreciated!

> Here's the temporary repo: https://github.com/Gavazzi1/CS4500-A2-Changes
> 
> We'll close this issue once the changes are integrated into this repo
