### ISSUE TITLE
toString() method for objects

### ISSUE THREAD

**Issue by egan-seamus** [carmen52/CS4500-A1-part2#3]
Currently objects, don't have a "toString" method. Please add one to your object class so that it can be implemented.

**Comment by Gavazzi1** [comment]
This was an oversight on our part when we adopted chasebish's object class. It would probably be better to remove the toString() method altogether, right?

**Comment by egan-seamus** [comment]
I agree with that, for the purposes of this assignment I don't think its necessary.

**Comment by Gavazzi1** [comment]
Cool, just pushed the changes
